backend:
  name: git-gateway
  branch: master 
media_folder: "_site/images/uploads"
public_folder: "/images/uploads"
collections:
  - label: "Configuration"
    name: "configuration"
    editor:
      preview: false
    files:
      - label: "Dates"
        name: "dates"
        file: "src/_data/dates.yaml"
        fields:
          - label: "Date/heure départ de la course"
            name: "dateCourse"
            widget: "datetime"
            default: ""
            date_format: "DD/MM/YYYY"
            tile_format: "HH:mm"
          - label: "Date de l'augmentation"
            name: "dateAugmentation"
            widget: "date"
            default: ""
            date_format: "DD/MM/YYYY"
          - label: "Date retrait des dossards"
            name: "dateRetrait"
            widget: "date"
            default: ""
            date_format: "DD/MM/YYYY"