backend:
  name: git-gateway
  branch: master 
local_backend: true
locale: fr
media_folder: "/images/uploads"
public_folder: "/images/uploads"
collections:
  - label: "Configuration"
    name: "configuration"
    editor:
      preview: false
    files:
      - label: "Dates"
        name: "dates"
        file: "src/_data/dates.yaml"
        fields:
          - label: "Date de l'augmentation"
            required: false
            hint: "Si vide, alors pas d'augmentation"
            name: "dateAugmentation"
            widget: "date"
            default: ""
            date_format: "DD/MM/YYYY"
          - label: "Date retrait des dossards"
            name: "dateRetrait"
            widget: "date"
            default: ""
            date_format: "DD/MM/YYYY"
          - label: "Date/heure départ de la course"
            name: "dateCourse"
            widget: "datetime"
            default: ""
            date_format: "DD/MM/YYYY"
            tile_format: "HH:mm"
      - label: "Contacts"
        name: "socials"
        file: "src/_data/socials.yaml"
        fields: 
          - label: "Facebook"
            name: "facebook"
            widget: "string"
            hint: "Lien vers la page de l'évènement sur Facebook"
          - label: "Mail"
            name: "mail"
            widget: "string"
            hint: "Adresse mail du club"
          - label: "Téléphone"
            name: "phone"
            widget: "string"
            hint: "Numéro de téléphone du club"
  - label: "Courses"
    name: "courses"
    editor:
      preview: false
    files: 
      - label: "Liens"
        name: "liens"
        file: "src/_data/courses/liens.yaml"
        fields: 
          - label: "Lien Inscription"
            name: "inscription"
            widget: "string"
            hint: "Lien vers la page d'inscription"
      - label: "Parcours court"
        name: "court"
        file: "src/_data/courses/court.yaml"
        fields: 
          - label: "Distance"
            name: "distance"
            widget: "number"
            value_type: "int"
            min: 0
          - label: "Parcours OpenRunner"
            name: "openrunner"
            widget: "string"
            hint: "Uniquement le lien"
          - label: "Tarif (en euros)"
            name: "tarif"
            widget: "number"
            value_type: "int"
            min: 0
          - label: "Augmentation (en euros ajoutés)"
            name: "augmentation"
            required: false
            widget: "number"
            value_type: "int"
            min: 0
          - label: "Classement Handisport"
            name: "handisport"
            required: true
            widget: "boolean"
          - label: "Compléments d'infos"
            name: "complements"
            widget: markdown
            buttons: [
              "bold",
              "italic",
              "link",
              "bulleted-list"
            ]
            required: false
          
      - label: "Parcours long"
        name: "long"
        file: "src/_data/courses/long.yaml"
        fields: 
          - label: "Distance"
            name: "distance"
            widget: "number"
            value_type: "int"
            min: 0
          - label: "Parcours OpenRunner"
            name: "openrunner"
            widget: "string"
            hint: "Uniquement le lien"
          - label: "Tarif (en euros)"
            name: "tarif"
            widget: "number"
            value_type: "int"
            min: 0
          - label: "Augmentation (en euros ajoutés)"
            name: "augmentation"
            required: false
            widget: "number"
            value_type: "int"
            min: 0
          - label: "Classement Handisport"
            name: "handisport"
            required: true
            widget: "boolean"
          - label: "Compléments d'infos"
            name: "complements"
            widget: markdown
            buttons: [
              "bold",
              "italic",
              "link",
              "bulleted-list"
            ]
            required: false
      - label: "Pousseurs"
        name: "pousseurs"
        file: "src/_data/courses/pousseurs.yaml"
        fields: 
          - label: "Réduction pousseurs"
            name: "reductionEnabled"
            widget: "boolean"
          - label: "Code promo"
            name: "coupon"
            widget: "string"
      - label: "Enfants"
        name: "enfants"
        file: "src/_data/courses/enfants.yaml"
        fields: 
          - label: "Informations"
            name: "informations"
            widget: markdown
            buttons: [
              "bold",
              "italic",
              "link",
              "bulleted-list"
            ]
            required: true

  - label: "Associations"
    name: "associations"
    editor:
      preview: false
    files:
      - label: "MARC"
        name: "marc"
        file: "src/_data/associations/marc.yaml"
        fields:
          - label: "Description"
            name: "description"
            widget: "text"
          - label: "Logo"
            name: "logo"
            widget: "image"
          - label: "Lien vers le site de l'association"
            name: "url"
            widget: "string"
      - label: "Bénéficiaire"
        name: "beneficiaire"
        file: "src/_data/associations/beneficiaire.yaml"
        fields:
          - label: "Nom"
            name: "name"
            widget: "string"
          - label: "Description"
            name: "description"
            widget: "text"
          - label: "Logo"
            name: "logo"
            widget: "image"
          - label: "Lien vers le site de l'association"
            name: "url"
            widget: "string"
  
  - label: "Programme"
    name: "programme"
    editor: 
      preview: false
    files: 
      - file: "src/_data/programme.yaml"
        label: Evènements
        name: evenements
        fields:
          - label: Evènements
            name: evenements
            summary :  '{{fields.datetime}} - {{fields.informations}}'
            widget: list
            hint: "L'ordre affiché ici correspond à l'affichage sur le site !"
            fields: 
              - label: Date et heure
                hint: au format JJ/MM/AAAA HH:mm
                name: "datetime"
                widget: "string"
                pattern: ['\d{2}/\d{2}/\d{4} \d{2}:\d{2}', "Vérifier le format"]
              - label: "Informations"
                name: "informations"
                widget: markdown
                buttons: [
                  "bold",
                  "italic",
                  "link"
                ]
                required: true
              - label: Type d'activité
                name: "type"
                widget: "select"
                options: 
                  - {label: "MARC", value: "right"}
                  - {label: "Partenaire", value: "left"}
                hint: Change la couleur de la pastille, vert pour MARC, rose pour le partenaire
  
  - label: "Sponsors"
    name: "sponsors"
    editor: 
      preview: false
    files: 
      - file: "src/_data/sponsors.yaml"
        label: Gestion des sponsors
        name: sponsors
        fields:
          - label: Sponsors
            name: sponsors
            summary : '{{fields.nom}}'
            widget: list
            
            fields: 
              - label: Nom du sponsor
                name: "nom"
                widget: "string"
              - label: Lien
                name: lien
                widget: string
              - label: Image
                name: image
                widget: image
                choose_url: false
                media_library:
                  config:
                    multiple: false
              - label: Importance
                hint: Fera apparaître le logo plus grand
                widget: "select"
                name: importance
                default: ''
                required: false
                options: 
                  - {label: normal, value: 'normal'}
                  - {label: important, value: 'important'}
                  - {label: très important, value: 'very-important'}
                  
