backend:
  name: git-gateway
  branch: master 
media_folder: "_site/images/uploads"
public_folder: "/images/uploads"
collections:
  - label: "Configuration"
    name: "configuration"
    editor:
      preview: false
    files:
      - label: "Dates"
        name: "dates"
        file: "src/_data/dates.yaml"
        fields:
          - label: "Date/heure départ de la course"
            name: "dateCourse"
            widget: "datetime"
            default: ""
            date_format: "DD/MM/YYYY"
            tile_format: "HH:mm"
          - label: "Date de l'augmentation"
            name: "dateAugmentation"
            widget: "date"
            default: ""
            date_format: "DD/MM/YYYY"
          - label: "Date retrait des dossards"
            name: "dateRetrait"
            widget: "date"
            default: ""
            date_format: "DD/MM/YYYY"
      - label: "Réseaux sociaux"
        name: "socials"
        file: "src/_data/socials.yaml"
        fields: 
          - label: "Facebook"
            name: "facebook"
            widget: "string"
            hint: "Lien vers la page de l'évènement sur Facebook"
            # pattern: ['/[(http(s)?):\/\/(www\.)?a-zA-Z0-9@:%._\+~#=]{2,256}\.[a-z]{2,6}\b([-a-zA-Z0-9@:%_\+.~#?&//=]*)/ig', 'Veuillez saisir une URL']
  